version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "angular",
    "vue",
    "angularjs"
  ]

[[analyzers]]
name = "test-coverage"

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"